services:
  - type: web
    name: slouma
    runtime: node
    rootDir: server
    buildCommand: npm install --omit=dev
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://slouma-vvp1.vercel.app
      - key: RESEND_API_KEY
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: EMAIL_FROM
        value: noreply@slouma.tn
    healthCheckPath: /api/health
    autoDeploy: true
