import express from "express";
import { createMessage, getMessages, getMessageById, updateMessage, deleteMessage, getContacts, getChatHistory, blockUser } from "../controllers/MessagesController.js";
const routerM = express.Router();
routerM.post('/', createMessage);
routerM.get('/', getMessages);
routerM.get('/:id', getMessageById);
routerM.put('/:id', updateMessage);
routerM.get('/:id/contacts', getContacts);
routerM.get('/:userId/history/:contactId', getChatHistory);
routerM.delete('/:userId/block/:contactId', blockUser);
routerM.delete('/:id', deleteMessage);
export default routerM;